"""Pydantic schemas for API requests, responses, and health diagnostics."""

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Chat Schemas
# ---------------------------------------------------------------------------

class SourceItem(BaseModel):
    """Grounding citation source metadata from RAG retrieval."""
    source_file: str
    guest_name: str
    chunk_index: int
    similarity: float
    content: str


class ArtifactPayload(BaseModel):
    """Structured artifact generated by the assistant."""
    type: str = Field(..., description="Artifact category, e.g. 'growth_loop', 'lno_audit'")
    title: Optional[str] = None
    content: str = Field(..., description="Markdown or structured payload")


class ChatRequest(BaseModel):
    """Request payload for /api/v1/chat endpoint."""
    message: str = Field(
        ...,
        min_length=1,
        max_length=8000,
        description="User message prompt (must not be empty)",
    )
    session_id: Optional[str] = Field(
        None,
        description="Existing session UUID, or omitted to automatically spawn a session",
    )
    provider: Literal["ollama", "anthropic"] = Field(
        "ollama",
        description="Selected LLM provider for runtime dynamic dispatch",
    )
    model: Optional[str] = Field(
        None,
        description="Optional model override (e.g. 'llama3.2', 'claude-3-5-sonnet-latest')",
    )
    mode: Literal["chat", "ship30"] = Field(
        "chat",
        description="Conversational mode: standard chat or Ship30 execution mode",
    )

    @field_validator("message")
    @classmethod
    def validate_message_not_empty(cls, v: str) -> str:
        trimmed = v.strip()
        if not trimmed:
            raise ValueError("Message prompt cannot be empty or whitespace only.")
        return trimmed


class ChatResponse(BaseModel):
    """Response payload for /api/v1/chat endpoint."""
    session_id: str
    message_id: int
    reply: str
    sources: List[SourceItem] = Field(default_factory=list)
    artifact: Optional[ArtifactPayload] = None
    provider_used: str


# ---------------------------------------------------------------------------
# Session & Message Schemas
# ---------------------------------------------------------------------------

class SessionCreateRequest(BaseModel):
    """Payload to explicitly initiate a new conversation session."""
    title: Optional[str] = Field(
        default="New Conversation",
        max_length=255,
        description="Initial session title",
    )


class MessageResponse(BaseModel):
    """Detailed representation of a conversation turn."""
    id: int
    session_id: str
    role: str
    content: str
    provider: Optional[str] = None
    sources: Optional[List[Dict[str, Any]]] = None
    artifact_type: Optional[str] = None
    artifact_content: Optional[str] = None
    created_at: datetime


class SessionResponse(BaseModel):
    """Complete representation of a session including thread messages."""
    id: str
    title: str
    created_at: datetime
    updated_at: datetime
    messages: List[MessageResponse] = Field(default_factory=list)


class SessionListResponse(BaseModel):
    """List of sessions for the sidebar/history."""
    sessions: List[SessionResponse]


# ---------------------------------------------------------------------------
# Health & Diagnostics Schemas
# ---------------------------------------------------------------------------

class HealthResponse(BaseModel):
    """System health check and provider readiness status."""
    status: Literal["healthy", "degraded"]
    database: bool
    ollama: bool
    providers_available: List[str]
